name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Configure Git
      run: |
        git config --global user.email "jonatan.ljung@hotmail.com"
        git config --global user.name "Jonatan Ljung"

    - name: Build
      run: npm run build -- --prod --base-href "https://jonlju95.github.io/jonlju95/"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/jonlju95.github.io/browser
